[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[dev]
  command = "npm run dev"
  port = 8888
  functions = "netlify/functions"
  targetPort = 5173
  environment = { DATABASE_URL = "postgresql://postgres.qkbmwomazqwxpyhdfrbw:Kri$n@1908!@@aws-1-ap-south-1.pooler.supabase.com:6543/postgres?pgbouncer=true" }

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/p/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/app/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/login"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/signup"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"
  included_files = ["netlify/functions/**"]
